version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: "America/Chihuahua"
    open-pull-requests-limit: 10
    reviewers: ["cetinajero"]
    labels:
      - dependencies
      - python
